name: Build & Deploy
on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy gp app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd app
            cd python-flask-mongoengine-docker-starter-master/
            git -c credential.helper= -c core.quotepath=false -c log.showSignature=false merge origin/pre_dev --no-stat -v
            docker-compose up --force-recreate --build -d
            echo 'Deployment successful to digital ocean' 
